version: '3.1'

services:
  mongo:
    container_name: wps-data-container
    image: mongo:3.6.8
    restart: always
    environment:
      MONGO_SERVER: localhost
      MONGO_INITDB_ROOT_USERNAME: productListUser
      MONGO_INITDB_ROOT_PASSWORD: productListPassword
    volumes:
      - ./entrypoint/products-entrypoint.sh:/docker-entrypoint-initdb.d/init.sh
      - ./database/products.json:/database/products.json
    ports:
      - "27017:27017"
